{{- $name := .Values.albserviceaccount.name | default "alb-ingress-controller" -}}
{{- $namespace := .Values.albserviceaccount.namespace | default "kube-system" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: <ARN OF YOUR ROLE HERE>